name: Build WEB
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter config --enable-web
      - run: flutter create --project-name mcrezil_game . --platforms web --overwrite
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: MCREZIL-WEBSITE
          path: build/web
